pipeline {
    agent any 

    tools {
        maven 'maven-3.9.5'
    }

    stages {
        stage ('Build-Maven') {
            steps {
                sh '''
                    cd ./maven/simple-war/
                    mvn clean package
                    cd ./target/
                    ls
                '''
            }
        }

        stage ('Deploy-Tomcat') {
            steps {
                script {
                    deploy adapters: [tomcat9(credentialsId: 'tomcat-manager', path: '', url: 'http://3.108.185.40:8080/')], 
                                     contextPath: '/calculator', 
                                     war: 'maven/calculator_app/target/calculator.war'
                    
                }
            }
        }
    }

}
